name: simpletodo_flutter
description: "A simple and modern Todo app built with Flutter."
publish_to: 'none'
version: 0.0.1+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  device_info_plus: ^10.1.0
  # State Management
  provider: ^6.0.0
  
  # Utility
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  timezone: ^0.9.2
  permission_handler: ^11.3.0
  
  # Notification
  flutter_local_notifications: ^17.0.0
  
  # UI
  flutter_slidable: ^3.0.0
  cupertino_icons: ^1.0.8
  
  # Monetization (Ads & Purchase)
  purchases_flutter: ^8.0.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Tooling (아이콘 생성기는 개발할 때만 쓰므로 여기 있는 게 정석입니다)
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

# 아이콘 설정
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true